sudo: required
language: java
install: true
jdk:
  - oraclejdk8
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
script:
  - mvn clean install -X

before_deploy:
  - pwd
  - export ARTIFACT_NAME=$(ls target/*.exe)
  - echo "Deploying $ARTIFACT_NAME to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: OWNUqFMwG2ZjmS6k1h9CPVDjBuMd8xPzO1fL9se//1wnQN4eiEZyuxsKW0CWoIdQQdSOOY7331u0UMiwI6iW4YyyaLKRf4wQx0MJ3yh6iot1PkAXOfCZaMaAjnoqaAu5BDqu88T8TOmVdVM+UHrvAqBHkp3cospn1ccDKX6EKmSgG4Wh8E7bKtC089DViePGK+mmzQnt35VXxDaSo1ocLmHfOa8PhBHG4ckakNCtyLn23531t7J0M+cHzQkW5CuoTM5JswuffEiIn/3ghc82mn8swYQO8q9WZ8QnaUptkHHq3+TU1jr6iUh0N/J7Rsyy1ktZ7k3dbUtbGcpgpbuI15INyAI7WktJEOPDxLXXPIpeWGQ5l0VAzfeTCgF5nDrjD4FxNBwyNgRt+1ZDDg3cLFbND8MtiM49tvMmqWQEbj1zyXJHRw1H/fglwzAfrTC+dFdfmT3dIofNkBpLoA0ftTu9WHvetF93GNIGGLltIXREsaEpscKlghcZxtbuoF8WFP5fTMTDnWgZzlP81SrypUlY/eGOtQb3VkxpytoDFHGKOkz3Gkq5Y4wgUFLWW/IJGv/sRXuZL+SdZdvHErb9szXX6EWyatlgVq0ZZwOyWbumqf6KODhV+8bq2nPS9SNhWmP/j9Y9JpajsjrW79Tdt7HZNDGmREbo5U/OR8dqhy0=
  file_glob: true
  file: ${ARTIFACT_NAME}
  skip_cleanup: true
  on:
    tags: true
    repo: salvatorenovelli/redirect-check-cl
